# Generated by Django 4.2.1 on 2024-10-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develops', '0002_alter_alexnor_options_alexnor_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alexnor',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
