# Generated by Django 4.2.1 on 2024-10-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develops', '0003_alter_alexnor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alexnor',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
